import streamlit as st
import pandas as pd
import plotly.express as px
import numpy as np
import os

st.set_page_config(page_title="Transcriptomics Exploration Engine", layout="wide")
st.title("🧬 OncoTranscript-TNBC — Biomarker Discovery Dashboard")

st.markdown("""
### Explore TNBC vs HR+ transcriptomic results from TCGA-BRCA + GSE58135 validation
Differential expression, pathway enrichment, and Random Forest biomarker classifier results — generated by the OncoTranscript-TNBC Nextflow pipeline.
""")

base_results = "results"
deg_file = os.path.join(base_results, "differential_expression", "deseq2_deg_results.csv")
biomarker_file = os.path.join(base_results, "ml_outputs", "biomarker_importances.csv")

if os.path.exists(deg_file):
    df_deg = pd.read_csv(deg_file).rename(columns={'Unnamed: 0': 'Gene'})
    df_deg['-log10(padj)'] = -np.log10(df_deg['padj'])

    col1, col2 = st.columns([1, 2])

    with col1:
        st.subheader("Filter Differential Expressions")
        p_cutoff = st.slider("Max Adjusted P-Value", 0.0001, 0.05, 0.01, step=0.001)
        lfc_cutoff = st.slider("Minimum Log2 Fold Change", 0.5, 4.0, 2.0, step=0.25)

        filtered_df = df_deg[(df_deg['padj'] <= p_cutoff) & (df_deg['log2FoldChange'].abs() >= lfc_cutoff)]
        st.metric("Significant De-regulated Transcripts", len(filtered_df))
        st.dataframe(filtered_df[['Gene', 'log2FoldChange', 'padj']].sort_values(by='padj'), height=300)

    with col2:
        st.subheader("Interactive Volcano Plot")
        df_deg['Expression'] = 'Not Significant'
        df_deg.loc[(df_deg['log2FoldChange'] >= lfc_cutoff) & (df_deg['padj'] <= p_cutoff), 'Expression'] = 'Upregulated'
        df_deg.loc[(df_deg['log2FoldChange'] <= -lfc_cutoff) & (df_deg['padj'] <= p_cutoff), 'Expression'] = 'Downregulated'

        fig = px.scatter(
            df_deg, x="log2FoldChange", y="-log10(padj)", color="Expression",
            hover_data=["Gene"],
            color_discrete_map={"Upregulated": "#e74c3c", "Downregulated": "#3498db", "Not Significant": "#bdc3c7"},
            labels={"log2FoldChange": "Log2 Fold Change", "-log10(padj)": "-log10(Adjusted P-Value)"},
        )
        st.plotly_chart(fig, use_container_width=True)
else:
    st.warning("Please execute the Nextflow and R downstream steps to populate the interactive visual frames.")
